- date: 2026-08-25
  name: "NeurIPS 2026 Agents Verification Workshop"
  type: Review Committee
  link: https://verify-agents-workshop.github.io/

- date: 2025-01-16
  name: "PLDI 2025"
  type: Artifact Evaluation Committee
  link: https://pldi25.sigplan.org/committee/pldi-2025-pldi-research-artifacts-artifact-evaluation-committee

- date: 2024-01-16
  name: "PLDI 2024"
  type: Artifact Evaluation Committee
  link: https://pldi24.sigplan.org/committee/pldi-2024-pldi-research-artifacts-artifact-evaluation-committee
