name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: true

    - name: Update Bundler
      run: |
        gem update --system
        gem install bundler

    - name: Install Ruby dependencies
      run: |
        gem uninstall uri -aIx || true
        gem install uri -v 1.0.2
        bundle install --clean

    - name: Install npm dependencies
      run: |
        if ! command -v npm &> /dev/null; then
          echo "npm not found! Please install Node.js and npm."
          exit 1
        fi
        npm install -g mermaid.cli

    - name: Setup deploy options
      env:
        SRC_BRANCH: ${{ github.head_ref || github.ref_name }}
        DEPLOY_BRANCH: gh-pages
        NO_PUSH: ${{ github.event_name == 'pull_request' && '--no-push' || '' }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Deploy website
      run: |
        set -e
        bash bin/deploy --verbose ${{ env.NO_PUSH }} --src ${{ env.SRC_BRANCH }} --deploy ${{ env.DEPLOY_BRANCH }}
